
service: cicd-aws

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: dev
  memorySize: 128
  environment:
    CUSTOMER_INFO: "customer-info"
    IS_OFFLINE: ${opt:is-offline}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:495730804023:table/customer-info"

    - Effect: "Allow"
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "arn:aws:lambda:us-east-1:*:*"

functions:
  hello:
    handler: handler/handler.hello
    events:
      - http:
          path: handler
          method: GET
          cors: true
  
  addCustomer:
    name: ${opt:stage}-addCustomer
    handler: customer/customerCRUD.addCustomer
    events:
      - http:
          path: addCustomer/{email}
          method: POST
          cors: true
  
  getCustomersList:
    name: ${opt:stage}-getCustomersList
    handler: customer/customerCRUD.getCustomersList
    events:
      - http:
          path: getCustomersList
          method: GET
          cors: true
          
  getCustomer:
    name: ${opt:stage}-getCustomer
    handler: customer/customerCRUD.getCustomer
    events:
      - http:
          path: getCustomer/{email}
          method: GET
          cors: true

  getCust:
    name: ${opt:stage}-getCust
    handler: customer/getCust.getCust
    events:
      - http:
          path: getCust
          method: GET
          cors: true
  
#Common functions:
  dynamodb: 
    name: ${opt:stage}-dynamodb
    handler: common/dynamodb.dynamoDB

  common:
    name: ${opt:stage}-common
    handler: common/common.common

  statusCode:
    name: ${opt:stage}-statusCode
    handler: common/statusCode.StatusCode

resources:
  Resources:
    customerInfo:
        Type: AWS::DynamoDB::Table
        DeletionPolicy: Retain
        Properties:
          TableName: customer-info
          AttributeDefinitions:
            - AttributeName: email
              AttributeType: S
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1