version: 2
jobs:
  build:
    environment:
      TERM: xterm

    docker:
      - image: circleci/node:8
      - image: lambci/lambda:latest
      - image: kalote/circleci-node8-jre

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Node dependencies
          command: npm install

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
        
      - run: 
          name: Setup serverless package
          command: sudo npm install serverless -g

      - run:
          name: Install serverless dynamodb offline - dependancy for serverless
          command: sls dynamodb install

      - run:
          name: run serverless offline for lambda functions
          command: npm start

      - run:
          name: Unit tests with coverage
          command: |
            ./cc-test-reporter before-build
            npm run test
            ./cc-test-reporter after-build --exit-code $?

      - run:
          name: Deploy application
          command: npm run deploy

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - store_test_results:
          path: coverage
