version: 2
jobs:
  build:
    environment:
      TERM: xterm
    
    docker:
      - image: circleci/node:8

  working_directory: ~/repo

  steps:
        - checkout
  - run:
            name: Install Node dependencies
            command: npm install
  - run:
            name: Unit tests
            command: npm test
  - run:
            name: Deploy to AWS
            command: npm run deploy

workflows:
  version: 2
  build:
    jobs:
      - build